[env]
TERM = "xterm-256color"

[cursor]
style = "Beam"

[font]
size = 13

[font.bold]
family = "Hack Nerd Font"
style = "Bold"

[font.italic]
family = "Hack Nerd Font"
style = "Bold Italic"

[font.normal]
family = "Hack Nerd Font"
style = "Regular"

[font.offset]
x = 1
y = 1

[scrolling]
history = 10000
multiplier = 1

[terminal.shell]
args = ["-l", "-c", "if tmux has-session 2>/dev/null; then tmux attach; else tmux new-session \\; run-shell 'tmux source-file ~/.tmux.conf'; fi"]
program = "/bin/zsh"

[window]
opacity = 0.95
title = "Alacritty"
resize_increments = true
option_as_alt = "Both"

[window.class]
general = "Alacritty"
instance = "Alacritty"

[window.dimensions]
columns = 180
lines = 52

[window.padding]
x = 1
y = 1

[colors.cursor]
text = "CellBackground"
cursor = "CellForeground"

[debug]

# log_level = "Error" # Default: "Warn"
log_level = "Warn" # Default: "Warn"

[general]
live_config_reload = true
import = ["/Users/k4ssyi/.config/alacritty/themes/themes/catppuccin.toml"]

[terminal]

