local vim.g.mapleader = "<Space>"
local keymap = vim.keymap

keymap.set("", ";;", "$", { noremap = true })
keymap.set("", "<S-h>", "0", { noremap = true })
keymap.set("", "<S-l>", "$", { noremap = true })
keymap.set("n", "あ", "a", { noremap = true })
keymap.set("n", "い", "i", { noremap = true })
keymap.set("n", "う", "u", { noremap = true })
keymap.set("n", "え", "e", { noremap = true })
keymap.set("n", "っy", "yy", { noremap = true })
keymap.set("n", "っd", "dd", { noremap = true })
keymap.set("n", "<leader>w", ":w<CR>", { noremap = true })
keymap.set("n", "Y", "y$")
keymap.set("n", "<C-n>", ":NeoTreeShowToggle<Return>", { noremap = true, silent = true })
keymap.set("n", "<C-j>", ":bnext<CR>", { silent = true, noremap = true })
keymap.set("n", "<C-k>", ":bprev<CR>", { silent = true, noremap = true })
keymap.set("n", "x", '"_x', { noremap = true, desc = "do not yank with x" })

keymap.set("i", "jj", "<Esc>", { silent = true, noremap = true })
keymap.set("i", "っj", "<Esc>", { silent = true, noremap = true })
keymap.set("i", "<C-j>", "<Down>", { noremap = true })
keymap.set("i", "<C-k>", "<Up>", { noremap = true })
keymap.set("i", "<C-h>", "<Left>", { noremap = true })
keymap.set("i", "<C-l>", "<Right>", { noremap = true })
keymap.set("i", "{", "{}<Left>", { noremap = true })
keymap.set("i", "[", "[]<Left>", { noremap = true })
keymap.set("i", "(", "()<Left>", { noremap = true })
keymap.set("i", '"', '""<Left>', { noremap = true })
keymap.set("i", "'", "''<Left>", { noremap = true })
keymap.set("i", "<C-e>", "<Esc>A", { desc = "Move to end of line" })
keymap.set("i", "<C-a>", "<Esc>I", { desc = "Move to start of line" })

keymap.set("v", "x", '"_x', { noremap = true, desc = "do not yank with x" })
