local opt = vim.opt

opt.swapfile = false
opt.helplang = "ja"
opt.syntax = "on"
opt.encoding = "utf-8"
opt.title = true
opt.number = true
opt.ruler = true
opt.smartcase = true
opt.cursorline = true
opt.shiftwidth = 2
opt.tabstop = 2
opt.hls = true
opt.clipboard = "unnamedplus"
opt.showmatch = true
opt.fileencodings = "utf-8"
opt.updatetime = 300
opt.laststatus = 2
opt.expandtab = true
opt.autoindent = true
opt.smartindent = true
